// <auto-generated />
namespace Validus_Code_Test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MusicContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MusicContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201801120019064_MusicContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
